version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: soup2-postgres
    restart: always
    environment:
      POSTGRES_DB: bd_semestr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0044
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: soup2-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bd_semestr
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0044
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_SECURITY_ENABLED: false
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

volumes:
  postgres_data: