spring.application.name=soup2
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_semestr
spring.datasource.username=postgres
spring.datasource.password=0044
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=project
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftlh
spring.freemarker.charset=UTF-8
spring.freemarker.check-template-location=true