spring.application.name=soup2
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_semestr
spring.datasource.username=postgres
spring.datasource.password=0044

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftlh
spring.freemarker.charset=UTF-8
spring.freemarker.check-template-location=true
spring.freemarker.expose-request-attributes=true


logging.level.ru.itis.soup2=DEBUG
logging.level.org.springframework.security=DEBUG
spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./uploads/,file:uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.error.include-stacktrace=always
server.error.include-exception=true
server.error.include-message=always

spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=
spring.mail.password=
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false